### ISSUE TITLE
Exception is suppressed when content-type is not specified

### ISSUE THREAD

**Issue by AdamRiddick** [Moesif/moesif-dotnet#36]
Hi,

We're working with some legacy systems which don't specify the content type for every API call - These calls are failing without any exceptions being raised as the exception is being handled by the MoesifMiddleware, though this is an empty handler.

This is in the .Net Framework middleware - haven't tested the DNX version.

As the usage is wrapped in the MoesifMiddleware, the exception is not surface due to the try....catch block.

As a temporary workaround we're having to set the content type if it is not set when the request comes in.

The request fails in the Serialize method of the LoggerHelper https://github.com/Moesif/moesif-dotnet/blob/c6882f5f6e4e0c020447e20af4dc3f3e4cf16668/Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs#L160

There is a null check around data, but not around content type.

These exceptions should also be surfaced in some way.

**Comment by dgilling** [comment]
Hi @AdamRiddick  thanks for letting us know, we'll have a fix tested and released shortly.

**Comment by dgilling** [comment]
Hi @AdamRiddick , we fixed this issue in version 1.3.3 if you're able to update your Nuget package.
