### ISSUE TITLE
Moesif.Middleware.nuspec does not include dependency on Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by dplaskon** [Moesif/moesif-dotnet#83]
This causes a runtime failure due to the missing reference if you don't happen to have an appropriate Microsoft.Extensions.Logging package already referenced in the project that uses it.

**Comment by praves77** [comment]
We will be releasing patch soon.

**Comment by praves77** [comment]
@dplaskon we've published version `1.4.5` and it fixes dependency issue too. Thanks for the patience.
