### ISSUE TITLE
Moesif.Middleware.nuspec specifies the wrong version of System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by dplaskon** [Moesif/moesif-dotnet#85]
From the nuspec:

<dependency id="System.IdentityModel.Tokens.Jwt" version="6.8.0" />

From the project file:

<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.2" />

This causes version conflict issues while building.

**Comment by keyur9** [comment]
Hello @dplaskon, we've published `1.4.6` which fixes the conflict issue. Thanks for letting us know!
